# Generated by Django 4.1.7 on 2023-04-17 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_userdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='basketproducts',
            name='count',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
