# Generated by Django 4.1.7 on 2023-04-17 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_basketproducts_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basketproducts',
            old_name='count',
            new_name='countOfProducts',
        ),
    ]
