# Generated by Django 4.1.7 on 2023-04-17 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_rename_count_basketproducts_countofproducts'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproducts',
            name='countOfProducts',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
