# Generated by Django 4.1.7 on 2023-05-04 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_orderproducts_countofproducts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Customer',
        ),
        migrations.RenameModel(
            old_name='UserDetails',
            new_name='CustomerDetails',
        ),
    ]
