# Generated by Django 4.1.7 on 2023-05-04 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_alter_basket_options_alter_basketproducts_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basket',
            options={'verbose_name': 'Кошик', 'verbose_name_plural': 'Кошики'},
        ),
        migrations.AlterModelOptions(
            name='basketproducts',
            options={'verbose_name': 'Товари кошику', 'verbose_name_plural': 'Товари кошиків'},
        ),
        migrations.AlterModelOptions(
            name='customerdetails',
            options={'verbose_name': 'Деталі клієнта', 'verbose_name_plural': 'Деталі клієнтів'},
        ),
        migrations.AlterModelOptions(
            name='orderproducts',
            options={'verbose_name': 'Продукти замовлення', 'verbose_name_plural': 'Продукти замовлень'},
        ),
    ]
