# Generated by Django 4.1.7 on 2023-05-26 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_alter_basket_options_alter_basketproducts_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(null=True, verbose_name='опис товару'),
        ),
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.TextField(null=True, verbose_name='Посилання на зображення'),
        ),
    ]
